Repository novoda/no-player, pull requests merged in 2018-04, with the labels that each got.

#141 ExoPlayer Dependency Update
  core/build.gradle
  demo/build.gradle
Labels: enhancement

#142 Only emit beat when the player is playing
  core/src/main/java/com/novoda/noplayer/internal/Heart.java
  core/src/test/java/com/novoda/noplayer/internal/HeartTest.java
Labels: bug

#145 Add Options to loadVideo
  core/src/main/java/com/novoda/noplayer/NoPlayer.java
  core/src/main/java/com/novoda/noplayer/Options.java
  core/src/main/java/com/novoda/noplayer/OptionsBuilder.java
  core/src/main/java/com/novoda/noplayer/internal/exoplayer/CompositeTrackSelectorCreator.java
  core/src/main/java/com/novoda/noplayer/internal/exoplayer/ExoPlayerFacade.java
  core/src/main/java/com/novoda/noplayer/internal/exoplayer/ExoPlayerTwoImpl.java
  core/src/main/java/com/novoda/noplayer/internal/mediaplayer/AndroidMediaPlayerImpl.java
  core/src/test/java/com/novoda/noplayer/internal/exoplayer/ExoPlayerFacadeTest.java
  core/src/test/java/com/novoda/noplayer/internal/exoplayer/ExoPlayerTwoImplTest.java
  core/src/test/java/com/novoda/noplayer/internal/mediaplayer/AndroidMediaPlayerImplTest.java
  demo/src/main/java/com/novoda/demo/DemoPresenter.java
  demo/src/main/java/com/novoda/demo/MainActivity.java
Labels: enhancement, feature

#148 Options to influence default track selection
  core/src/main/java/com/novoda/noplayer/NoPlayer.java
  core/src/main/java/com/novoda/noplayer/Options.java
  core/src/main/java/com/novoda/noplayer/OptionsBuilder.java
  core/src/main/java/com/novoda/noplayer/PlayerBuilder.java
  core/src/main/java/com/novoda/noplayer/internal/exoplayer/CompositeTrackSelector.java
  core/src/main/java/com/novoda/noplayer/internal/exoplayer/CompositeTrackSelectorCreator.java
  core/src/main/java/com/novoda/noplayer/internal/exoplayer/ExoPlayerCreator.java
  core/src/main/java/com/novoda/noplayer/internal/exoplayer/ExoPlayerFacade.java
  core/src/main/java/com/novoda/noplayer/internal/exoplayer/ExoPlayerTwoImpl.java
  core/src/main/java/com/novoda/noplayer/internal/exoplayer/NoPlayerExoPlayerCreator.java
  core/src/main/java/com/novoda/noplayer/internal/mediaplayer/AndroidMediaPlayerImpl.java
  core/src/test/java/com/novoda/noplayer/internal/exoplayer/ExoPlayerFacadeTest.java
  core/src/test/java/com/novoda/noplayer/internal/exoplayer/ExoPlayerTwoImplTest.java
  core/src/test/java/com/novoda/noplayer/internal/mediaplayer/AndroidMediaPlayerImplTest.java
  demo/src/main/java/com/novoda/demo/DemoPresenter.java
  demo/src/main/java/com/novoda/demo/MainActivity.java
Labels: enhancement, feature
