Repository novoda/no-player, pull requests merged in 2019-06, with the labels that each got.

#246 Allow no-player to skip a given advert break
  core/build.gradle
  core/src/main/java/com/novoda/noplayer/NoPlayer.java
  core/src/main/java/com/novoda/noplayer/SimpleAdvertListener.java
  core/src/main/java/com/novoda/noplayer/internal/exoplayer/AvailableAdverts.java
  core/src/main/java/com/novoda/noplayer/internal/exoplayer/ExoPlayerFacade.java
  core/src/main/java/com/novoda/noplayer/internal/exoplayer/ExoPlayerTwoImpl.java
  core/src/main/java/com/novoda/noplayer/internal/exoplayer/NoOpAdvertListener.java
  core/src/main/java/com/novoda/noplayer/internal/exoplayer/NoPlayerAdsLoader.java
  core/src/main/java/com/novoda/noplayer/internal/exoplayer/SkippedAdverts.java
  core/src/main/java/com/novoda/noplayer/internal/listeners/AdvertListeners.java
  core/src/main/java/com/novoda/noplayer/internal/mediaplayer/AndroidMediaPlayerFacade.java
  core/src/main/java/com/novoda/noplayer/internal/mediaplayer/AndroidMediaPlayerImpl.java
  core/src/test/java/com/novoda/noplayer/internal/exoplayer/SkippedAdvertsTest.java
Labels: enhancement

#248 Notify advert break ends if last advert if skipped
  core/src/main/java/com/novoda/noplayer/internal/exoplayer/NoPlayerAdsLoader.java
Labels: bug

#251 Show adverts even on seek
  core/src/main/java/com/novoda/noplayer/internal/exoplayer/AvailableAdverts.java
  core/src/main/java/com/novoda/noplayer/internal/exoplayer/ExoPlayerFacade.java
  core/src/main/java/com/novoda/noplayer/internal/exoplayer/NoPlayerAdsLoader.java
  core/src/main/java/com/novoda/noplayer/internal/exoplayer/NoPlayerExoPlayerCreator.java
  core/src/test/java/com/novoda/noplayer/internal/exoplayer/AvailableAdvertsTest.java
  core/src/test/java/com/novoda/noplayer/internal/exoplayer/ExoPlayerFacadeTest.java
  core/src/test/java/com/novoda/noplayer/internal/exoplayer/NoPlayerAdsLoaderTest.java
Labels: enhancement

#252 Allow secure and non-secure decoders
  core/src/main/java/com/novoda/noplayer/internal/exoplayer/SecurityDowngradingCodecSelector.java
  core/src/test/java/com/novoda/noplayer/internal/exoplayer/SecurityDowngradingCodecSelectorTest.java
Labels: bug

#254 Secure and non-secure codecs
  core/src/main/java/com/novoda/noplayer/NoPlayerCreator.java
  core/src/main/java/com/novoda/noplayer/PlayerBuilder.java
  core/src/main/java/com/novoda/noplayer/internal/exoplayer/CodecSelectorWithFallback.java
  core/src/main/java/com/novoda/noplayer/internal/exoplayer/ExoPlayerCreator.java
  core/src/main/java/com/novoda/noplayer/internal/exoplayer/ExoPlayerFacade.java
  core/src/main/java/com/novoda/noplayer/internal/exoplayer/ExoPlayerTwoImpl.java
  core/src/main/java/com/novoda/noplayer/internal/exoplayer/MediaCodecAudioRendererWithSimplifiedDrmRequirement.java
  core/src/main/java/com/novoda/noplayer/internal/exoplayer/MediaCodecVideoRendererWithSimplifiedDrmRequirement.java
  core/src/main/java/com/novoda/noplayer/internal/exoplayer/NoPlayerExoPlayerCreator.java
  core/src/main/java/com/novoda/noplayer/internal/exoplayer/SimpleRenderersFactory.java
  core/src/test/java/com/novoda/noplayer/internal/exoplayer/CodecSelectorWithFallbackTest.java
  core/src/test/java/com/novoda/noplayer/internal/exoplayer/ExoPlayerFacadeTest.java
  core/src/test/java/com/novoda/noplayer/internal/exoplayer/ExoPlayerTwoImplTest.java
  demo/src/main/java/com/novoda/demo/MainActivity.java
Labels: enhancement

#256 Advert resume position
  core/src/main/java/com/novoda/noplayer/internal/exoplayer/AdvertPlaybackState.java
  core/src/main/java/com/novoda/noplayer/internal/exoplayer/NoPlayerAdsLoader.java
  core/src/main/java/com/novoda/noplayer/internal/exoplayer/ResumeableAdverts.java
  core/src/test/java/com/novoda/noplayer/internal/exoplayer/AdvertPlaybackStateTest.java
  core/src/test/java/com/novoda/noplayer/internal/exoplayer/ResumeableAdvertsTest.java
Labels: bug

#257 Custom playback parameters
  core/src/main/java/com/novoda/noplayer/internal/exoplayer/TextRendererOutput.java
  demo/build.gradle
  demo/src/main/AndroidManifest.xml
  demo/src/main/java/com/novoda/demo/LandingActivity.java
  demo/src/main/java/com/novoda/demo/MainActivity.java
  demo/src/main/res/layout/activity_landing.xml
  demo/src/main/res/values/strings.xml
  demo/src/main/res/values/styles.xml
Labels: enhancement

#258 Downloaded license
  demo/build.gradle
  demo/src/main/java/com/novoda/demo/LandingActivity.java
  demo/src/main/java/com/novoda/demo/MainActivity.java
  demo/src/main/java/com/novoda/demo/OfflineLicense.java
  demo/src/main/java/com/novoda/demo/PlaybackParameters.java
Labels: enhancement

#262 DrmSession rework
  core/src/main/java/com/novoda/noplayer/NoPlayerCreator.java
  core/src/main/java/com/novoda/noplayer/PlayerBuilder.java
  core/src/main/java/com/novoda/noplayer/drm/DownloadedModularDrm.java
  core/src/main/java/com/novoda/noplayer/drm/DrmHandler.java
  core/src/main/java/com/novoda/noplayer/drm/KeyRequestExecutor.java
  core/src/main/java/com/novoda/noplayer/internal/exoplayer/drm/DownloadDrmSessionCreator.java
  core/src/main/java/com/novoda/noplayer/internal/exoplayer/drm/DrmSessionCreatorFactory.java
  core/src/main/java/com/novoda/noplayer/internal/exoplayer/drm/ExoPlayerDrmSessionCreator.java
  core/src/main/java/com/novoda/noplayer/internal/exoplayer/drm/StreamingDrmSessionCreator.java
  core/src/test/java/com/novoda/noplayer/NoPlayerCreatorTest.java
  core/src/test/java/com/novoda/noplayer/internal/exoplayer/drm/DrmSessionCreatorFactoryTest.java
  demo/src/main/java/com/novoda/demo/MainActivity.java
Labels: enhancement

#263 Feature/DRM rework
  core/src/main/java/com/novoda/noplayer/NoPlayerCreator.java
  core/src/main/java/com/novoda/noplayer/PlayerBuilder.java
  core/src/main/java/com/novoda/noplayer/drm/DownloadedModularDrm.java
  core/src/main/java/com/novoda/noplayer/drm/DrmHandler.java
  core/src/main/java/com/novoda/noplayer/drm/KeyRequestExecutor.java
  core/src/main/java/com/novoda/noplayer/internal/exoplayer/drm/DownloadDrmSessionCreator.java
  core/src/main/java/com/novoda/noplayer/internal/exoplayer/drm/DrmSessionCreator.java
  core/src/main/java/com/novoda/noplayer/internal/exoplayer/drm/DrmSessionCreatorFactory.java
  core/src/main/java/com/novoda/noplayer/internal/exoplayer/drm/ExoPlayerDrmSessionCreator.java
  core/src/main/java/com/novoda/noplayer/internal/exoplayer/drm/NoDrmSessionCreator.java
  core/src/main/java/com/novoda/noplayer/internal/exoplayer/drm/ProvisioningModularDrmCallback.java
  core/src/main/java/com/novoda/noplayer/internal/exoplayer/drm/StreamingDrmSessionCreator.java
  core/src/test/java/com/novoda/noplayer/NoPlayerCreatorTest.java
  core/src/test/java/com/novoda/noplayer/internal/exoplayer/drm/DrmSessionCreatorFactoryTest.java
  demo/src/main/java/com/novoda/demo/DataPostingModularDrm.java
  demo/src/main/java/com/novoda/demo/MainActivity.java
Labels: feature

#264 Revert DRM expiry check
  core/src/main/java/com/novoda/noplayer/internal/exoplayer/drm/ExoPlayerDrmSessionCreator.java
Labels: bug

#260 Advert loader state rework
  core/src/main/java/com/novoda/noplayer/internal/exoplayer/NoPlayerAdsLoader.java
Labels: discussion, enhancement

#265 Codec capabilities
  core/src/main/java/com/novoda/noplayer/internal/exoplayer/CodecSelectorWithFallback.java
  core/src/main/java/com/novoda/noplayer/internal/exoplayer/InternalMediaCodecUtil.java
  core/src/main/java/com/novoda/noplayer/internal/exoplayer/MediaCodecAudioRendererWithSimplifiedDrmRequirement.java
  core/src/main/java/com/novoda/noplayer/internal/exoplayer/MediaCodecVideoRendererWithSimplifiedDrmRequirement.java
  core/src/test/java/com/novoda/noplayer/internal/exoplayer/CodecSelectorWithFallbackTest.java
Labels: bug

#266 Resumeable adverts
  core/src/main/java/com/novoda/noplayer/internal/exoplayer/ExoPlayerFacade.java
  core/src/main/java/com/novoda/noplayer/internal/exoplayer/NoPlayerAdsLoader.java
  core/src/main/java/com/novoda/noplayer/internal/exoplayer/ResumeableAdverts.java
  core/src/test/java/com/novoda/noplayer/internal/exoplayer/ExoPlayerFacadeTest.java
  core/src/test/java/com/novoda/noplayer/internal/exoplayer/NoPlayerAdsLoaderTest.java
  core/src/test/java/com/novoda/noplayer/internal/exoplayer/ResumeableAdvertsTest.java
Labels: bug
