Repository novoda/no-player, pull requests merged in 2019-04, with the labels that each got.

#211 Deprecate `playAt` for seeking initial position
  core/src/main/java/com/novoda/noplayer/NoPlayer.java
  core/src/main/java/com/novoda/noplayer/Options.java
  core/src/main/java/com/novoda/noplayer/OptionsBuilder.java
  core/src/main/java/com/novoda/noplayer/internal/exoplayer/ExoPlayerFacade.java
  core/src/test/java/com/novoda/noplayer/internal/exoplayer/ExoPlayerFacadeTest.java
Labels: bug

#212 NO-ADS/Skipping adverts based on start position
  core/src/main/java/com/novoda/noplayer/internal/exoplayer/NoPlayerAdsLoader.java
  core/src/main/java/com/novoda/noplayer/internal/exoplayer/SkippedAdverts.java
  core/src/test/java/com/novoda/noplayer/AdvertBreakFixtures.java
  core/src/test/java/com/novoda/noplayer/internal/exoplayer/SkippedAdvertsTest.java
Labels: feature

#213 Add max video bitrate
  core/src/main/java/com/novoda/noplayer/NoPlayer.java
  core/src/main/java/com/novoda/noplayer/Options.java
  core/src/main/java/com/novoda/noplayer/OptionsBuilder.java
  core/src/main/java/com/novoda/noplayer/internal/exoplayer/CompositeTrackSelector.java
  core/src/main/java/com/novoda/noplayer/internal/exoplayer/CompositeTrackSelectorCreator.java
  core/src/main/java/com/novoda/noplayer/internal/exoplayer/ExoPlayerFacade.java
  core/src/main/java/com/novoda/noplayer/internal/exoplayer/ExoPlayerTwoImpl.java
  core/src/main/java/com/novoda/noplayer/internal/exoplayer/mediasource/ExoPlayerTrackSelector.java
  core/src/main/java/com/novoda/noplayer/internal/exoplayer/mediasource/ExoPlayerVideoTrackSelector.java
  core/src/main/java/com/novoda/noplayer/internal/mediaplayer/AndroidMediaPlayerFacade.java
  core/src/main/java/com/novoda/noplayer/internal/mediaplayer/AndroidMediaPlayerImpl.java
  core/src/test/java/com/novoda/noplayer/internal/exoplayer/mediasource/ExoPlayerVideoTrackSelectorTest.java
  demo/src/main/java/com/novoda/demo/MainActivity.java
  demo/src/main/res/layout/activity_main.xml
  demo/src/main/res/values/strings.xml
Labels: feature

#217 NO-ADS/Skipping Events
  core/src/main/java/com/novoda/noplayer/internal/exoplayer/NoPlayerAdsLoader.java
Labels: bug

#218 NO-ADS/Advert View
  core/src/main/java/com/novoda/noplayer/AdvertView.java
  core/src/main/java/com/novoda/noplayer/NoPlayer.java
  core/src/main/java/com/novoda/noplayer/SimpleAdvertListener.java
  core/src/main/java/com/novoda/noplayer/internal/exoplayer/ExoPlayerFacade.java
  core/src/main/java/com/novoda/noplayer/internal/exoplayer/ExoPlayerTwoImpl.java
  core/src/main/java/com/novoda/noplayer/internal/exoplayer/NoOpAdvertListener.java
  core/src/main/java/com/novoda/noplayer/internal/exoplayer/NoPlayerAdsLoader.java
  core/src/main/java/com/novoda/noplayer/internal/listeners/AdvertListeners.java
  core/src/main/java/com/novoda/noplayer/internal/mediaplayer/AndroidMediaPlayerFacade.java
  core/src/main/java/com/novoda/noplayer/internal/mediaplayer/AndroidMediaPlayerImpl.java
  core/src/test/java/com/novoda/noplayer/internal/exoplayer/NoPlayerAdsLoaderTest.java
Labels: feature

#220 NO-ADS/Add click through URI to the Advert model
  core/src/main/java/com/novoda/noplayer/Advert.java
  core/src/test/java/com/novoda/noplayer/AdvertFixtures.java
Labels: enhancement

#221 NO-ADS/Skipping adverts bug
  core/src/main/java/com/novoda/noplayer/internal/exoplayer/NoPlayerAdsLoader.java
Labels: bug

#222 NO-ADS/Enable Disable Adverts
  core/src/main/java/com/novoda/noplayer/NoPlayer.java
  core/src/main/java/com/novoda/noplayer/SimpleAdvertListener.java
  core/src/main/java/com/novoda/noplayer/internal/exoplayer/AvailableAdverts.java
  core/src/main/java/com/novoda/noplayer/internal/exoplayer/ExoPlayerFacade.java
  core/src/main/java/com/novoda/noplayer/internal/exoplayer/ExoPlayerTwoImpl.java
  core/src/main/java/com/novoda/noplayer/internal/exoplayer/NoOpAdvertListener.java
  core/src/main/java/com/novoda/noplayer/internal/exoplayer/NoPlayerAdsLoader.java
  core/src/main/java/com/novoda/noplayer/internal/exoplayer/PlayedAdverts.java
  core/src/main/java/com/novoda/noplayer/internal/exoplayer/SkippedAdverts.java
  core/src/main/java/com/novoda/noplayer/internal/listeners/AdvertListeners.java
  core/src/main/java/com/novoda/noplayer/internal/mediaplayer/AndroidMediaPlayerFacade.java
  core/src/main/java/com/novoda/noplayer/internal/mediaplayer/AndroidMediaPlayerImpl.java
  core/src/test/java/com/novoda/noplayer/internal/exoplayer/AdvertPlaybackStateTest.java
  core/src/test/java/com/novoda/noplayer/internal/exoplayer/AvailableAdvertsTest.java
  core/src/test/java/com/novoda/noplayer/internal/exoplayer/PlayedAdvertsTest.java
  core/src/test/java/com/novoda/noplayer/internal/exoplayer/SkippedAdvertsTest.java
Labels: enhancement, feature

#223 NO-ADS/Add callback for played ads
  core/src/main/java/com/novoda/noplayer/NoPlayer.java
  core/src/main/java/com/novoda/noplayer/SimpleAdvertListener.java
  core/src/main/java/com/novoda/noplayer/internal/exoplayer/NoOpAdvertListener.java
  core/src/main/java/com/novoda/noplayer/internal/exoplayer/NoPlayerAdsLoader.java
  core/src/main/java/com/novoda/noplayer/internal/exoplayer/PlayedAdverts.java
  core/src/main/java/com/novoda/noplayer/internal/listeners/AdvertListeners.java
  core/src/test/java/com/novoda/noplayer/internal/exoplayer/PlayedAdvertsTest.java
Labels: bug

#230 Update snapshot releases
  README.md
  core/build.gradle
Labels: bug

#225 NO-ADS/feature
  core/src/main/java/com/novoda/noplayer/Advert.java
  core/src/main/java/com/novoda/noplayer/AdvertBreak.java
  core/src/main/java/com/novoda/noplayer/AdvertBreakId.java
  core/src/main/java/com/novoda/noplayer/AdvertId.java
  core/src/main/java/com/novoda/noplayer/AdvertView.java
  core/src/main/java/com/novoda/noplayer/AdvertsLoader.java
  core/src/main/java/com/novoda/noplayer/Listeners.java
  core/src/main/java/com/novoda/noplayer/NoPlayer.java
  core/src/main/java/com/novoda/noplayer/PlayerBuilder.java
  core/src/main/java/com/novoda/noplayer/PlayerState.java
  core/src/main/java/com/novoda/noplayer/SimpleAdvertListener.java
  core/src/main/java/com/novoda/noplayer/internal/exoplayer/AdvertBreakStartTimeComparator.java
  core/src/main/java/com/novoda/noplayer/internal/exoplayer/AdvertPlaybackState.java
  core/src/main/java/com/novoda/noplayer/internal/exoplayer/AvailableAdverts.java
  core/src/main/java/com/novoda/noplayer/internal/exoplayer/ExoPlayerFacade.java
  core/src/main/java/com/novoda/noplayer/internal/exoplayer/ExoPlayerTwoImpl.java
  core/src/main/java/com/novoda/noplayer/internal/exoplayer/NoOpAdvertListener.java
  core/src/main/java/com/novoda/noplayer/internal/exoplayer/NoPlayerAdsLoader.java
  core/src/main/java/com/novoda/noplayer/internal/exoplayer/NoPlayerExoPlayerCreator.java
  core/src/main/java/com/novoda/noplayer/internal/exoplayer/PlayedAdverts.java
  core/src/main/java/com/novoda/noplayer/internal/exoplayer/SkippedAdverts.java
  core/src/main/java/com/novoda/noplayer/internal/exoplayer/forwarder/ExoPlayerForwarder.java
  core/src/main/java/com/novoda/noplayer/internal/exoplayer/mediasource/MediaSourceFactory.java
  core/src/main/java/com/novoda/noplayer/internal/listeners/AdvertListeners.java
  core/src/main/java/com/novoda/noplayer/internal/listeners/PlayerListenersHolder.java
  core/src/main/java/com/novoda/noplayer/internal/mediaplayer/AndroidMediaPlayerFacade.java
  core/src/main/java/com/novoda/noplayer/internal/mediaplayer/AndroidMediaPlayerImpl.java
  core/src/test/java/com/novoda/noplayer/AdvertBreakFixtures.java
  core/src/test/java/com/novoda/noplayer/AdvertFixtures.java
  core/src/test/java/com/novoda/noplayer/internal/exoplayer/AdvertBreakStartTimeComparatorTest.java
  core/src/test/java/com/novoda/noplayer/internal/exoplayer/AdvertPlaybackStateTest.java
  core/src/test/java/com/novoda/noplayer/internal/exoplayer/AvailableAdvertsTest.java
  core/src/test/java/com/novoda/noplayer/internal/exoplayer/ExoPlayerFacadeTest.java
  core/src/test/java/com/novoda/noplayer/internal/exoplayer/NoPlayerAdsLoaderTest.java
  core/src/test/java/com/novoda/noplayer/internal/exoplayer/PlayedAdvertsTest.java
  core/src/test/java/com/novoda/noplayer/internal/exoplayer/SkippedAdvertsTest.java
Labels: feature
