Repository novoda/no-player, pull requests merged in 2019-05, with the labels that each got.

#234 NO-ADS/Update condition of isPlayingAdvert
  core/src/main/java/com/novoda/noplayer/PlayerState.java
  core/src/main/java/com/novoda/noplayer/internal/exoplayer/ExoPlayerFacade.java
  core/src/main/java/com/novoda/noplayer/internal/exoplayer/ExoPlayerTwoImpl.java
  core/src/main/java/com/novoda/noplayer/internal/mediaplayer/AndroidMediaPlayerImpl.java
  core/src/test/java/com/novoda/noplayer/internal/exoplayer/ExoPlayerFacadeTest.java
Labels: enhancement, housekeeping

#236 Advert live playback
  core/src/main/java/com/novoda/noplayer/NoPlayer.java
  core/src/main/java/com/novoda/noplayer/SimpleAdvertListener.java
  core/src/main/java/com/novoda/noplayer/internal/exoplayer/NoOpAdvertListener.java
  core/src/main/java/com/novoda/noplayer/internal/exoplayer/NoPlayerAdsLoader.java
  core/src/main/java/com/novoda/noplayer/internal/exoplayer/PlayedAdverts.java
  core/src/main/java/com/novoda/noplayer/internal/listeners/AdvertListeners.java
  core/src/test/java/com/novoda/noplayer/internal/exoplayer/PlayedAdvertsTest.java
Labels: bug

#239 Update dependencies
  core/build.gradle
  core/src/main/java/com/novoda/noplayer/Advert.java
  core/src/main/java/com/novoda/noplayer/DetailErrorType.java
  core/src/main/java/com/novoda/noplayer/NoPlayer.java
  core/src/main/java/com/novoda/noplayer/PlayerSurfaceHolder.java
  core/src/main/java/com/novoda/noplayer/PlayerViewSurfaceHolder.java
  core/src/main/java/com/novoda/noplayer/external/exoplayer/text/webvtt/WebvttCueParser.java
  core/src/main/java/com/novoda/noplayer/internal/drm/provision/ProvisioningCapabilities.java
  core/src/main/java/com/novoda/noplayer/internal/exoplayer/ExoPlayerCreator.java
  core/src/main/java/com/novoda/noplayer/internal/exoplayer/ExoPlayerFacade.java
  core/src/main/java/com/novoda/noplayer/internal/exoplayer/ExoPlayerTwoImpl.java
  core/src/main/java/com/novoda/noplayer/internal/exoplayer/NoPlayerAdsLoader.java
  core/src/main/java/com/novoda/noplayer/internal/exoplayer/NoPlayerExoPlayerCreator.java
  core/src/main/java/com/novoda/noplayer/internal/exoplayer/SecurityDowngradingCodecSelector.java
  core/src/main/java/com/novoda/noplayer/internal/exoplayer/SimpleRenderersFactory.java
  core/src/main/java/com/novoda/noplayer/internal/exoplayer/drm/DrmSessionCreator.java
  core/src/main/java/com/novoda/noplayer/internal/exoplayer/drm/InvalidDrmSession.java
  core/src/main/java/com/novoda/noplayer/internal/exoplayer/drm/LocalDrmSession.java
  core/src/main/java/com/novoda/noplayer/internal/exoplayer/drm/NoDrmSessionCreator.java
  core/src/main/java/com/novoda/noplayer/internal/exoplayer/error/ErrorFormatter.java
  core/src/main/java/com/novoda/noplayer/internal/exoplayer/error/ExoPlayerErrorMapper.java
  core/src/main/java/com/novoda/noplayer/internal/exoplayer/forwarder/BitrateForwarder.java
  core/src/main/java/com/novoda/noplayer/internal/exoplayer/forwarder/MediaSourceEventForwarder.java
  core/src/main/java/com/novoda/noplayer/internal/exoplayer/forwarder/NoPlayerMediaSourceEventListener.java
  core/src/main/java/com/novoda/noplayer/internal/mediaplayer/AndroidMediaPlayerFacade.java
  core/src/test/java/com/google/android/exoplayer2/drm/FrameworkMediaCryptoFixture.java
  core/src/test/java/com/novoda/noplayer/internal/exoplayer/SecurityDowngradingCodecSelectorTest.java
  core/src/test/java/com/novoda/noplayer/internal/exoplayer/drm/LocalDrmSessionManagerTest.java
  demo/build.gradle
  demo/src/main/java/com/novoda/demo/AndroidControllerView.java
  gradle.properties
Labels: enhancement

#241 Set advert break initial position
  core/src/main/java/com/novoda/noplayer/Options.java
  core/src/main/java/com/novoda/noplayer/OptionsBuilder.java
  core/src/main/java/com/novoda/noplayer/internal/exoplayer/AdvertPlaybackState.java
  core/src/main/java/com/novoda/noplayer/internal/exoplayer/ExoPlayerFacade.java
  core/src/main/java/com/novoda/noplayer/internal/exoplayer/NoPlayerAdsLoader.java
  core/src/test/java/com/novoda/noplayer/internal/exoplayer/AdGroupFixture.java
  core/src/test/java/com/novoda/noplayer/internal/exoplayer/AdvertPlaybackStateTest.java
  core/src/test/java/com/novoda/noplayer/internal/exoplayer/ExoPlayerFacadeTest.java
  core/src/test/java/com/novoda/noplayer/internal/exoplayer/NoPlayerAdsLoaderTest.java
Labels: enhancement

#242 Guard agains null when accessing track info
  core/src/main/java/com/novoda/noplayer/internal/exoplayer/mediasource/ExoPlayerTrackSelector.java
Labels: bug

#243 Seeking backwards plays adverts
  core/src/main/java/com/novoda/noplayer/internal/exoplayer/NoPlayerAdsLoader.java
  core/src/main/java/com/novoda/noplayer/internal/exoplayer/NoPlayerExoPlayerCreator.java
  core/src/main/java/com/novoda/noplayer/internal/exoplayer/SkippedAdverts.java
  core/src/test/java/com/novoda/noplayer/internal/exoplayer/SkippedAdvertsTest.java
Labels: enhancement

#244 Video type is lost when error is notified
  core/src/main/java/com/novoda/noplayer/PlayerState.java
  core/src/main/java/com/novoda/noplayer/internal/exoplayer/ExoPlayerFacade.java
  core/src/main/java/com/novoda/noplayer/internal/exoplayer/ExoPlayerTwoImpl.java
  core/src/main/java/com/novoda/noplayer/internal/mediaplayer/AndroidMediaPlayerImpl.java
  core/src/test/java/com/novoda/noplayer/internal/exoplayer/ExoPlayerFacadeTest.java
  core/src/test/java/com/novoda/noplayer/internal/exoplayer/ExoPlayerTwoImplTest.java
  core/src/test/java/com/novoda/noplayer/internal/mediaplayer/AndroidMediaPlayerImplTest.java
Labels: enhancement

#245 Mark adverts as skipped before content resume position
  core/src/main/java/com/novoda/noplayer/internal/exoplayer/ExoPlayerFacade.java
  core/src/main/java/com/novoda/noplayer/internal/exoplayer/NoPlayerAdsLoader.java
  core/src/main/java/com/novoda/noplayer/internal/exoplayer/SkippedAdverts.java
  core/src/test/java/com/novoda/noplayer/internal/exoplayer/ExoPlayerFacadeTest.java
  core/src/test/java/com/novoda/noplayer/internal/exoplayer/NoPlayerAdsLoaderTest.java
  core/src/test/java/com/novoda/noplayer/internal/exoplayer/SkippedAdvertsTest.java
Labels: enhancement
